
const types = {
  SET_USER: 'SET_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  DARK_THEME: 'DARK_THEME',
  LIGHT_THEME: 'LIGHT_THEME',
  SET_LOADER: 'SET_LOADER',
  STOP_LOADER: 'STOP_LOADER',
  SET_ACTIVE: 'SET_ACTIVE',
  SET_CHATROOM: 'SET_CHATROOM',
  CLOSE_CHATROOM: 'CLOSE_CHATROOM',
  SET_CONNECTION: 'SET_CONNECTION',
  SET_CONVERSATION: 'SET_CONVERSATION',
}

export default types